### ISSUE TITLE
Crash when turning on stream after killing through notifications

### ISSUE THREAD

**Issue by SkyeOfBreeze** [remotv/controller-for-android#114]
**Describe the bug**

2020-12-26 13:09:20.711 11619-11619/tv.remo.android.controller E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tv.remo.android.controller, PID: 11619
    java.lang.IllegalStateException
        at tv.remo.android.controller.ServiceInterface.changeStreamState(ServiceInterface.kt:54)
        at tv.remo.android.controller.activities.MainActivity.onClick(MainActivity.kt:65)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**To Reproduce**
1. Open the app
2. Go to the home screen
3. Terminate app via notifications
4. Open app from recents
5. Try to turn it on

**Expected behavior**
App enables stream

**Actual**
App crashes

**Smartphone (please complete the following information):**
 - Google Pixel 3A
 - OS: Android 11
 - App Version: Develop (https://github.com/remotv/controller-for-android/commit/d65f80fb787730c2085aff53bbd2ec869bcf6026)

**Comment by SkyeOfBreeze** [comment]
This is exactly what is happening. Splash screen loads the service, and the main activity uses it
https://stackoverflow.com/questions/29497349/app-restarts-from-wrong-activity
