### ISSUE TITLE
App crashes when going outside of range of hotspot, or having it turned off

### ISSUE THREAD

**Issue by SkyeOfBreeze** [remotv/controller-for-android#52]
**To Reproduce**
1. Turn on the hotspot
2. Connect the main robot phone to the hotspot
3. Turn on the robot, and wait for the video to stabilize
4. Turn hotspot off

**Expected behavior**
App will crash

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S4
 - OS: Android 5.0
 - App Version v0.9.3-beta

**Additional context**
This might be from it switching back to a known WiFi, but not sure yet. Having issues getting the logs to output the reason for the crash other than FFmpeg failing, which does not produce crashes on its own

**Comment by SkyeOfBreeze** [comment]
```
tv.remo.android.controller E/AndroidRuntime: FATAL EXCEPTION: AudioComponent
    Process: tv.remo.android.controller, PID: 15319
    java.io.IOException: write failed: EPIPE (Broken pipe)
        at libcore.io.IoBridge.write(IoBridge.java:502)
        at java.io.FileOutputStream.write(FileOutputStream.java:186)
        at java.io.OutputStream.write(OutputStream.java:82)
        at org.btelman.controlsdk.streaming.utils.OutputStreamUtil.handleSendByteArray(OutputStreamUtil.kt:32)
        at org.btelman.controlsdk.streaming.audio.processors.FFmpegAudioProcessor.processAudioByteArray(FFmpegAudioProcessor.kt:67)
        at org.btelman.controlsdk.streaming.components.AudioComponent.doWorkLoop(AudioComponent.kt:23)
        at org.btelman.controlsdk.streaming.components.StreamComponent.fetchFrame(StreamComponent.kt:47)
        at org.btelman.controlsdk.streaming.components.StreamComponent.handleMessage(StreamComponent.kt:40)
        at org.btelman.controlsdk.models.Component$handler$1.handleMessage(Component.kt:44)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
        at libcore.io.Posix.writeBytes(Native Method)
        at libcore.io.Posix.write(Posix.java:223)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
        at libcore.io.IoBridge.write(IoBridge.java:497)
        at java.io.FileOutputStream.write(FileOutputStream.java:186) 
        at java.io.OutputStream.write(OutputStream.java:82) 
        at org.btelman.controlsdk.streaming.utils.OutputStreamUtil.handleSendByteArray(OutputStreamUtil.kt:32) 
        at org.btelman.controlsdk.streaming.audio.processors.FFmpegAudioProcessor.processAudioByteArray(FFmpegAudioProcessor.kt:67) 
        at org.btelman.controlsdk.streaming.components.AudioComponent.doWorkLoop(AudioComponent.kt:23) 
        at org.btelman.controlsdk.streaming.components.StreamComponent.fetchFrame(StreamComponent.kt:47) 
        at org.btelman.controlsdk.streaming.components.StreamComponent.handleMessage(StreamComponent.kt:40) 
        at org.btelman.controlsdk.models.Component$handler$1.handleMessage(Component.kt:44) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
